# Generated by Django 3.1.3 on 2020-12-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='fujian',
            field=models.CharField(blank=True, default='upload/noPicture.jpg', max_length=200),
        ),
    ]
